from .tag_type import *
from .page import *
from .prez import *
from .post import *
from .tag import *
from .collection import *
from .urls import *
from .langs import *
from .list import *
from .redirection import *
